-- Migrated from monitors.conf; edit this Lua file going forward.
local v = require("variables")

-- Generated by nwg-displays on 2026-09-27 at 03:15:00. Do not edit manually.

hl.monitor({ ["output"] = "HDMI-A-1", ["mode"] = "3840x2160@60.0", ["position"] = "3000x0", ["scale"] = "1.5" })
hl.monitor({ ["output"] = "DP-2", ["mode"] = "1920x1080@60.0", ["position"] = "2280x0", ["scale"] = "1.5", ["transform"] = 1 })
