-- Native Lua configuration: UserConfigs/UserDecorations.lua.
local v = require("variables")

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Decoration Settings

-- Hyprland Wiki Links
-- Animation - https://wiki.hyprland.org/Configuring/Animations/
-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by wallust
require("wallust/wallust-hyprland")

hl.config({ ["general.border_size"] = 0 })
hl.config({ ["general.gaps_in"] = 2 })
hl.config({ ["general.gaps_out"] = 4 })

hl.config({ ["general.col.active_border"] = "rgba(00000000)" })
hl.config({ ["general.col.inactive_border"] = v.color10 })

hl.config({ ["decoration.rounding"] = 10 })

hl.config({ ["decoration.active_opacity"] = 1.0 })
hl.config({ ["decoration.inactive_opacity"] = 0.9 })
hl.config({ ["decoration.fullscreen_opacity"] = 1.0 })

hl.config({ ["decoration.dim_inactive"] = true })
hl.config({ ["decoration.dim_strength"] = 0.1 })
hl.config({ ["decoration.dim_special"] = 0.8 })

hl.config({ ["decoration.shadow.enabled"] = true })
hl.config({ ["decoration.shadow.range"] = 3 })
hl.config({ ["decoration.shadow.render_power"] = 1 })

hl.config({ ["decoration.shadow.color"] = "rgba(00000000)" })
hl.config({ ["decoration.shadow.color_inactive"] = v.color10 })


hl.config({ ["decoration.blur.enabled"] = true })
hl.config({ ["decoration.blur.size"] = 6 })
hl.config({ ["decoration.blur.passes"] = 2 })
hl.config({ ["decoration.blur.ignore_opacity"] = true })
hl.config({ ["decoration.blur.new_optimizations"] = true })
hl.config({ ["decoration.blur.special"] = true })
hl.config({ ["decoration.blur.popups"] = true })

hl.config({ ["group.col.border_active"] = v.color15 })

hl.config({ ["group.groupbar.col.active"] = v.color0 })
